apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "sqs-puller.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: sqs-puller
  template:
    metadata:
      labels:
        app: sqs-puller
    spec:
      containers:
        - name: {{ include "sqs-puller.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.targetPort }}
          envFrom:
            - configMapRef:
                name: {{ include "sqs-puller.fullname" . }}-config
          env:
            - name: AWS_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.aws.secretName }}
                  key: AWS_ACCESS_KEY
            - name: AWS_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.aws.secretName }}
                  key: AWS_SECRET_KEY
